env           :
  browser : true
  es2021  : true
extends       :
  - eslint:recommended
  - plugin:react/recommended
parserOptions :
  ecmaFeatures :
    jsx : true
  ecmaVersion  : latest
  sourceType   : module
plugins       :
  - react
rules         : {
  indent                             : [ warn, 2 ],
  semi                               : [ warn, never ],
  no-unused-vars                     : [ warn, { args : all } ],
  jsx-quotes                         : [ warn, prefer-single ],
  quotes                             : [ warn, single ],
  quote-props                        : [ warn, as-needed ],
  no-dupe-keys                       : error,
  eqeqeq                             : [ error, always ],
  no-console                         : [ warn, { allow : [ warn, error ] } ],
  #  one-var                           : [ error, consecutive ],
  one-var-declaration-per-line       : [ warn, always ],
  brace-style                        : [ warn, stroustrup, { allowSingleLine : true } ],
  block-spacing                      : warn,
  no-trailing-spaces                 : warn,
  space-before-blocks                : warn,
  space-infix-ops                    : warn,
  space-unary-ops                    : [ error,{ "words" : true, "nonwords" : false } ],
  arrow-body-style                   : [ warn, as-needed ],
  prefer-arrow-callback              : [ warn, { allowNamedFunctions : true } ],
  arrow-parens                       : [ warn, as-needed ],
  implicit-arrow-linebreak           : [ warn, beside ],
  no-confusing-arrow                 : [ warn ],
  arrow-spacing                      : warn,
  curly                              : [ warn, multi-or-nest ],
  comma-dangle                       : [ warn, { objects : always-multiline } ],
  comma-spacing                      : [ warn, { before : false, after : true } ],
  object-curly-spacing               : [ warn, always ],
  array-bracket-spacing              : [ warn, always ],
  #  prefer-destructuring: [ error, { AssignmentExpression: { array: true, object: true } } ],
  #  'no-redeclare'                    : [ error, { builtinGlobals: true } ],
#  no-shadow                          : [ error,{ builtinGlobals : true, hoist : all } ],
  #  react/jsx-sort-props                               : [ warn, { callbacksLast : true,
  #                                                                 shorthandLast : true,
  #                                                                 multiline     : ignore,
  #                                                                 ignoreCase    : true,
  #                                                                 reservedFirst : true,
  #  } ],
  react/jsx-sort-props               : [ warn, { callbacksLast        : true,
                                                 shorthandLast        : true,
                                                 multiline            : last,
                                                 ignoreCase           : true,
                                                 noSortAlphabetically : false,
                                                 reservedFirst        : true,
  } ],
  react/jsx-max-props-per-line       : [ warn, { maximum : { single : 3, multi : 1 } } ],
  react/jsx-first-prop-new-line      : [ warn, multiline ],
  react/jsx-one-expression-per-line  : [ warn, { allow : single-child } ], #  //none | literal | single-child
  react/jsx-wrap-multilines          : [ warn, { declaration : parens,
                                                 assignment  : parens,
                                                 return      : parens-new-line,
                                                 arrow       : parens-new-line,
                                                 condition   : ignore,
                                                 logical     : ignore,
                                                 prop        : ignore
  } ],
  react/jsx-closing-bracket-location : [ warn ],
  #    react/jsx-indent                  : [ error, 2 ],
  react/jsx-newline                  : [ error, { prevent : true } ],
  react/display-name                 : [ 0 ],
  #  react/react-in-jsx-scope                           : [ 0 ],
  react/no-access-state-in-setstate  : [ error ],
  'react/no-children-prop'           : 0,
  'no-case-declarations'             : 0,
  react/prop-types                   : 0
}
